---
# handlers file for wordpress

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart mysqld
  service:
    name: mysqld
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
